import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import torch

indices = torch.load('indices_tensor_fsbnn.pt')
print(indices[0:10])

arr = np.load('l1_wtheta_sm.npy')

epochs = arr.shape[0]
features = arr.shape[1]
hidden_dim = arr.shape[2]

plt.figure(figsize = (10,25))
plt.subplot(2,5,1)
plt.plot(arr[:,indices[0],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[0],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[0],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[0],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[0],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[0]))
plt.legend()

plt.subplot(2,5,2)
plt.plot(arr[:,indices[1],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[1],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[1],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[1],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[1],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[1]))
plt.legend()

plt.subplot(2,5,3)
plt.plot(arr[:,indices[2],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[2],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[2],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[2],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[2],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[2]))
plt.legend()

plt.subplot(2,5,4)
plt.plot(arr[:,indices[3],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[3],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[3],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[3],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[3],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[3]))
plt.legend()

plt.subplot(2,5,5)
plt.plot(arr[:,indices[4],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[4],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[4],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[4],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[4],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[4]))
plt.legend()

plt.subplot(2,5,6)
plt.plot(arr[:,indices[5],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[5],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[5],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[5],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[5],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[5]))
plt.legend()

plt.subplot(2,5,7)
plt.plot(arr[:,indices[6],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[6],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[6],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[6],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[6],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[6]))
plt.legend()

plt.subplot(2,5,8)
plt.plot(arr[:,indices[7],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[7],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[7],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[7],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[7],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[7]))
plt.legend()

plt.subplot(2,5,9)
plt.plot(arr[:,indices[8],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[8],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[8],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[8],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[8],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[8]))
plt.legend()

plt.subplot(2,5,10)
plt.plot(arr[:,indices[9],0], color = 'tab:brown', label = 'Hidden Dim 0')
plt.plot(arr[:,indices[9],1], color = 'tab:cyan', label = 'Hidden Dim 1')
plt.plot(arr[:,indices[9],2], color = 'tab:blue', label = 'Hidden Dim 2')
plt.plot(arr[:,indices[9],3], color = 'tab:green', label = 'Hidden Dim 3')
plt.plot(arr[:,indices[9],4], color = 'tab:red', label = 'Hidden Dim 4')
plt.xlabel('Iterations/Epochs')
plt.ylabel('Weights')
plt.title('Feature:{}'.format(indices[9]))
plt.legend()

plt.show()